import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/Theme";
import Footer from "../components/Footer";
import ContactHistoryProvider from "@/lib/FuncyFriend";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenKeeper",
  description: "Generated by Shakhawat Sadik",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className={`min-h-full min-w-full flex flex-col bg-background text-foreground transition-all duration-300`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ContactHistoryProvider>
            <Navbar />
            {children}
            <Footer />
          </ContactHistoryProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
